name: deployment
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm i
      - run: npm run build
      - name: rsync deploy
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -havz
          remote_host: ${{ secrets.SERVER_IP_ADDRESS }}
          remote_user: ${{ secrets.SERVER_USERNAME }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}
          remote_port: 22
          path: ".output/"
          remote_path: "/srv/http/website/"
      - name: restart node
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: systemctl restart website-node